name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      
    - name: Build application
      run: npm run build
      
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Package extension
      run: |
        mkdir -p dist
        cp manifest.json popup.html popup.js background.js content.js icon.png dist/
        cd dist && zip -r ../extension.zip *
    
    - name: Create Chrome extension version
      id: create_version
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: extension.zip
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        publish: true
        
    - name: Output version
      run: echo "Successfully published version ${{ steps.create_version.outputs.version }}"
